using System;
using System.Collections.Generic;

[Serializable]
/// <summary>
/// DTO class used to obtain history blocks generated by <see cref="GameManager::ConvertHistoryToBlocks"/> object.
/// </summary>
public class ConvertHistoryToBlocksDTO
{
    /// <summary>
    /// List of true events that happened in the story
    /// </summary>
    public List<string> key_events;
    
    /// <summary>
    /// List of false events
    /// </summary>
    public List<string> false_events;

    /// <summary>
    /// ToString override used for pretty printing
    /// </summary>
    /// <returns>Pretty print of the object</returns>
    public override string ToString() => $"HistoryBlocks:\nKey events:\n{string.Join('\n', key_events)}\nFalse events:\n{string.Join('\n', false_events)}";
}
